name: PyPI

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install rye
        uses: eifinger/setup-rye@v1
        with:
          enable-cache: true
          cache-prefix: "rye"

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: .venv
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements*.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          rye config --set-bool behavior.use-uv=true
          rye sync

      - name: Build package distributions
        run: |
          rye build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.9
